name: Luosi-Justrunmy.app-AutoRenew

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write  # 允许修改 cookie.txt
  actions: write   # 允许清理 workflow 记录

jobs:
  run_renewal:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          # 注意：如果是本仓库，可以直接去掉 repository 那行，更简洁
          repository: zhangbin0301/Luosi-Justrunmy.app-AutoRenew
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt -q > /dev/null 2>&1

    - name: Run Main Script
      env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py

    - name: Update README with Last Run Time
      if: success()
      run: |
        LAST_RUN=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
        echo "最后执行时间: $LAST_RUN"
        # 匹配 README.md 中的 标记并替换其下一行
        # 如果 README 中没有该标记，这一步不会报错但也不会生效
        sed -i "//{n;s/.*/Last Check-in: $LAST_RUN (Beijing Time)/;}" README.md  

    - name: Commit and Push Changes
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # 独立检查每个文件，有变动才 add
        [[ -n $(git status -s cookie.txt) ]] && git add cookie.txt && echo "Added cookie.txt"
        [[ -n $(git status -s README.md) ]] && git add README.md && echo "Added README.md"
        
        # 只有在暂存区有变动时才提交
        if ! git diff --cached --exit-code > /dev/null; then
          git commit -m "chore: auto update status/cookie [skip ci]"
          git push
        else
          echo "没有任何变动，跳过提交。"
        fi

    - name: Upload Error Screenshot
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: error.png

    - name: Clean up old workflow runs
      uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        repository: ${{ github.repository }}
        older-than-seconds: 86400  # 删除24小时前的记录
